version: '3'
services:
    frontend:
        build:
            context: ./frontend
            args:
              - ENV=development
        command: npm run serve
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/home/node/app:cached
            - /home/node/app/node_modules
    backend:
        build:
            context: .
            args:
              - DEBUG=True
        command:
            ["/app/wait-for-postgres.sh", "db", "${POSTGRES_PASSWORD}", "python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
            - "8000:8000"
        volumes:
            - .:/app:cached
        depends_on:
            - frontend
            - db
    db:
        image: "postgres:11.2-alpine"
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/