version: '3'
services:
    frontend:
        build: ./frontend
        restart: always
        command: npm run serve
        environment:
             - NODE_ENV=${NODE_ENV}
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/home/node/app/frontend:cached
            - /home/node/app/frontend/node_modules
        depends_on:
            - backend
    backend:
        build: .
        restart: always
        command:
            ["/app/wait-for-postgres.sh", "db", "${POSTGRES_PASSWORD}", "python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
            - "8000:8000"
        volumes:
            - .:/app:cached
        depends_on:
            - db
    db:
        image: "postgres:11.2-alpine"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres